//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNet.WebHooks.ConnectedService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNet.WebHooks.ConnectedService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the secrets you expect your incoming providers will provide on inbound requests.
        /// </summary>
        internal static string AddConfigurationSettingsWizardPageDescription {
            get {
                return ResourceManager.GetString("AddConfigurationSettingsWizardPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string AddConfigurationSettingsWizardPageLegend {
            get {
                return ResourceManager.GetString("AddConfigurationSettingsWizardPageLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your receivers.
        /// </summary>
        internal static string AddConfigurationSettingsWizardPageTitle {
            get {
                return ResourceManager.GetString("AddConfigurationSettingsWizardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET.
        /// </summary>
        internal static string ConnectedServiceCategory {
            get {
                return ResourceManager.GetString("ConnectedServiceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which WebHook providers you want to support in your ASP.NET application.
        /// </summary>
        internal static string ConnectedServiceDialogDescription {
            get {
                return ResourceManager.GetString("ConnectedServiceDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET WebHooks.
        /// </summary>
        internal static string ConnectedServiceDialogTitle {
            get {
                return ResourceManager.GetString("ConnectedServiceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive WebHooks from services such as GitHub and DropBox using ASP.NET WebHooks.
        /// </summary>
        internal static string ConnectedServiceListDescription {
            get {
                return ResourceManager.GetString("ConnectedServiceListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebHooks.
        /// </summary>
        internal static string ConnectedServiceProjectFolderName {
            get {
                return ResourceManager.GetString("ConnectedServiceProjectFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving WebHooks core NuGet packages.
        /// </summary>
        internal static string LogMessageGettingCoreNuGets {
            get {
                return ResourceManager.GetString("LogMessageGettingCoreNuGets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving WebHook Receiver NuGet for {0}.
        /// </summary>
        internal static string LogMessageGettingReceiver {
            get {
                return ResourceManager.GetString("LogMessageGettingReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.microsoft.com/fwlink/?LinkId=690277.
        /// </summary>
        internal static string MoreInfoUrl {
            get {
                return ResourceManager.GetString("MoreInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the third-party WebHooks you want to receive.
        /// </summary>
        internal static string SelectWebHooksPageDescription {
            get {
                return ResourceManager.GetString("SelectWebHooksPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivers.
        /// </summary>
        internal static string SelectWebHooksPageLegend {
            get {
                return ResourceManager.GetString("SelectWebHooksPageLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable incoming WebHook requests.
        /// </summary>
        internal static string SelectWebHooksPageTitle {
            get {
                return ResourceManager.GetString("SelectWebHooksPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap webhook {
            get {
                object obj = ResourceManager.GetObject("webhook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
